/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { T } from 'solid-three'
import { useGLTF } from '~/lib/useGLTF'
import { Resource } from 'solid-js'

type GLTFResult = GLTF & {
  nodes: {
    NURBS_Forr: THREE.Mesh
    Tapa_143: THREE.Mesh
    Tapa_52: THREE.Mesh
    Cilin97: THREE.Mesh
    Cubo1: THREE.Mesh
    _1: THREE.Mesh
    _2: THREE.Mesh
    NURBS: THREE.Mesh
    NURBS_Extr: THREE.Mesh
    cabina_0: THREE.Mesh
    ['646001']: THREE.Mesh
    ['895001']: THREE.Mesh
    Tapa_160: THREE.Mesh
    cabina_1: THREE.Mesh
    Tapa_156: THREE.Mesh
    Tapa_36: THREE.Mesh
    cabina_2: THREE.Mesh
    Tapa_154: THREE.Mesh
    Tapa_38: THREE.Mesh
    Cubo24: THREE.Mesh
    Esfer10: THREE.Mesh
    Pir_mide: THREE.Mesh
    Cubo4: THREE.Mesh
    pista: THREE.Mesh
    Tapa_152: THREE.Mesh
    Tapa_40: THREE.Mesh
  }
  materials: {
    ['Metal - High Ca']: THREE.MeshStandardMaterial
    ['Metal - Alumini']: THREE.MeshStandardMaterial
    ['Mat.6']: THREE.MeshStandardMaterial
    ['Mat.4']: THREE.MeshStandardMaterial
    ['Mat.5']: THREE.MeshStandardMaterial
    Mat12: THREE.MeshStandardMaterial
    ['Asphalt-03']: THREE.MeshStandardMaterial
  }
}

export function Carrier(props: JSX.IntrinsicElements['T.Group']) {
  const data = useGLTF('/carrier.glb') as Resource<GLTFResult>
  return (
    <T.Group {...props} dispose={null}>
      <T.Group position={[0, -0.5, 3]} scale={0.04}>
        <Show when={data()} keyed>
          {({ nodes, materials }) => (
            <>
              <T.Group position={[0, 10.93, 31.4]} scale={[0.8, 1.17, 1.29]}>
                <T.Mesh
                  geometry={nodes.NURBS_Forr.geometry}
                  material={materials['Metal - High Ca']}
                  position={[0, -9.33, -24.36]}
                  scale={[1.25, 0.85, 0.78]}>
                  <T.Mesh
                    geometry={nodes.Tapa_143.geometry}
                    material={materials['Metal - High Ca']}
                    position={[0, 12.41, 31.4]}
                    scale={[0.8, 1.17, 1.29]}
                  />
                  <T.Mesh
                    geometry={nodes.Tapa_52.geometry}
                    material={materials['Metal - High Ca']}
                    position={[0, -6.85, 0]}
                    scale={0.74}
                  />
                </T.Mesh>
              </T.Group>
              <T.Group position={[-12.33, 42.62, -61.98]}>
                <T.Mesh
                  geometry={nodes.Cilin97.geometry}
                  material={materials['Metal - Alumini']}
                  position={[0, 4.11, 0]}
                />
                <T.Mesh geometry={nodes.Cubo1.geometry} material={materials['Mat.6']} position={[3.67, 6.29, 0]} />
              </T.Group>
              <T.Group position={[0, -4.86, 0]}>
                <T.Group position={[8.08, 17.64, 72.42]} rotation={[-Math.PI / 2, 0, 0]}>
                  <T.Mesh geometry={nodes._1.geometry} material={materials['Mat.4']} />
                  <T.Mesh geometry={nodes._2.geometry} material={materials['Mat.4']} position={[5.01, 0, 0]} />
                </T.Group>
                <T.Mesh geometry={nodes.NURBS.geometry} material={materials['Mat.4']} position={[-20, -42.25, 0]} />
                <T.Mesh
                  geometry={nodes.NURBS_Extr.geometry}
                  material={materials['Mat.4']}
                  position={[-32.1, -42.25, 0]}
                />
              </T.Group>
              <T.Group position={[-12.25, 38.77, -65.42]} scale={[0.67, 1, 1]}>
                <T.Mesh geometry={nodes.cabina_0.geometry} material={materials['Mat.5']}>
                  <T.Group position={[-10.17, -11.58, -35.05]} scale={0.9}>
                    <T.Mesh geometry={nodes['646001'].geometry} material={materials.Mat12} />
                    <T.Mesh geometry={nodes['895001'].geometry} material={materials['Mat.5']} />
                  </T.Group>
                  <T.Mesh
                    geometry={nodes.Tapa_160.geometry}
                    material={materials['Mat.5']}
                    position={[-10.17, -27.65, -35.05]}
                  />
                </T.Mesh>
                <T.Mesh geometry={nodes.cabina_1.geometry} material={materials['Mat.5']} position={[0, 7.5, 0]}>
                  <T.Mesh
                    geometry={nodes.Tapa_156.geometry}
                    material={materials['Mat.5']}
                    position={[-10.17, -27.65, -35.05]}
                  />
                  <T.Mesh
                    geometry={nodes.Tapa_36.geometry}
                    material={materials['Mat.5']}
                    position={[-10.17, -11.58, -35.05]}
                    scale={0.9}
                  />
                </T.Mesh>
                <T.Mesh geometry={nodes.cabina_2.geometry} material={materials['Mat.5']} position={[0, 15, 0]}>
                  <T.Mesh
                    geometry={nodes.Tapa_154.geometry}
                    material={materials['Mat.5']}
                    position={[-10.17, -27.65, -35.05]}
                  />
                  <T.Mesh
                    geometry={nodes.Tapa_38.geometry}
                    material={materials['Mat.5']}
                    position={[-10.17, -11.58, -35.05]}
                    scale={0.9}
                  />
                </T.Mesh>
              </T.Group>
              <T.Group position={[-19.34, 41.91, -96.94]}>
                <T.Mesh
                  geometry={nodes.Cubo24.geometry}
                  material={materials['Metal - Alumini']}
                  position={[0, 13.27, 0]}
                />
                <T.Mesh
                  geometry={nodes.Esfer10.geometry}
                  material={materials['Metal - Alumini']}
                  position={[0, 16.84, 0]}
                />
                <T.Mesh
                  geometry={nodes.Pir_mide.geometry}
                  material={materials['Metal - High Ca']}
                  position={[0, 8.57, 0]}
                />
              </T.Group>
              <T.Mesh
                geometry={nodes.Cubo4.geometry}
                material={materials['Metal - High Ca']}
                position={[-18.56, 42.46, -100.72]}
              />
              <T.Mesh
                geometry={nodes.pista.geometry}
                material={materials['Asphalt-03']}
                position={[3.38, -6.16, 0]}
                scale={[1, 1, 1.62]}>
                <T.Mesh
                  geometry={nodes.Tapa_152.geometry}
                  material={materials['Asphalt-03']}
                  position={[-26.52, 18.92, -41.67]}
                />
                <T.Mesh
                  geometry={nodes.Tapa_40.geometry}
                  material={materials['Asphalt-03']}
                  position={[-26.52, 18.07, -41.67]}
                />
              </T.Mesh>
            </>
          )}
        </Show>
      </T.Group>
    </T.Group>
  )
}
