/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { T } from 'solid-three'
import { useGLTF } from '~/lib/useGLTF'

export function Cruise(props) {
  const data = useGLTF('/CruiseShip.glb')
  return (
    <T.Group {...props} dispose={null}>
      <Show when={data()} keyed>
        {({ nodes, materials }) => (
          <T.Group rotation={[0, Math.PI, 0]} scale={0.7}>
            <T.Mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.F2F2F2} />
            <T.Mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.Texture} />
            <T.Mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={materials.Red} />
            <T.Mesh castShadow receiveShadow geometry={nodes.Cube_3.geometry} material={materials.Black} />
          </T.Group>
        )}
      </Show>
    </T.Group>
  )
}
