/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Clonk (https://sketchfab.com/Clonk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/origami-ships-and-boats-5bccd248d9944204890b99924bcfb232
title: Origami - Ships and Boats
*/

import * as THREE from 'three'
import { useGLTF } from '../lib/useGLTF'
import { GLTF } from 'three-stdlib'
import { ComponentProps, Resource } from 'solid-js'
import { T } from 'solid-three'
import { BISHOP, KING, KNIGHT, PAWN, QUEEN, ROOK, WHITE } from '../lib/chess'
import { PieceSymbol } from '~/lib/chess/types'

type GLTFResult = GLTF & {
  nodes: {
    Plane010_Ships_0: THREE.Mesh
    Plane011_Ships_0: THREE.Mesh
    Plane013_Ships_0: THREE.Mesh
    Plane014_Ships_0: THREE.Mesh
    Plane015_Ships_0: THREE.Mesh
    Plane016_Ships_0: THREE.Mesh
    Plane017_Ships_0: THREE.Mesh
    Plane018_Ships_0: THREE.Mesh
    Plane019_Ships_0: THREE.Mesh
    Plane021_Ships_0: THREE.Mesh
    Plane023_Ships_0: THREE.Mesh
    Plane024_Ships_0: THREE.Mesh
    Plane026_Ships_0: THREE.Mesh
  }
  materials: {
    Ships: THREE.MeshStandardMaterial
  }
}

const PIECES = {
  [KING]: 'Plane019_Ships_0',
  [KNIGHT]: 'Plane024_Ships_0',
  [QUEEN]: 'Plane026_Ships_0',
  [PAWN]: 'Plane017_Ships_0',
  [ROOK]: 'Plane013_Ships_0',
  [BISHOP]: 'Plane014_Ships_0',
}

export function Ships(props: ComponentProps<typeof T.Group> & { piece: PieceSymbol }) {
  const data = useGLTF('/origami_-_ships_and_boats.glb') as Resource<GLTFResult>
  return (
    <T.Group {...props}>
      <Show when={data()} keyed>
        {(data) => (
          <>
            <T.Group scale={0.02}>
              <T.Mesh castShadow receiveShadow geometry={data.nodes[PIECES[props.piece]]?.geometry}>
                <T.MeshLambertMaterial color={props.color === WHITE ? 'white' : '#7c2d12'} />
              </T.Mesh>
            </T.Group>
            {/*                 
                <T.Group position={[100, 0, -200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane010_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[-99.999977, 0, 200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane011_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[200, 0, 0]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane013_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[-0.000024, 0, -200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane014_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[0.000024, 0, 0]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane015_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[100, 0, 0]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane016_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[-100, 0, 0]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane017_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[-100, 0, -200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane018_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[-200, 0, 0]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane019_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[0, 0, 200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane021_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[-200, 0, -200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane023_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[200, 0, -200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane024_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group>
                <T.Group position={[100, 0, 200]}>
                  <T.Mesh
                    castShadow
                    receiveShadow
                    geometry={data.nodes.Plane026_Ships_0.geometry}
                    material={data.materials.Ships}
                  />
                </T.Group> */}
          </>
        )}
      </Show>
    </T.Group>
  )
}
